### ISSUE TITLE
How to use Theme: APEX 5.0 in apex5.1

### ISSUE THREAD

**Issue by dpccrt87** [iMingLei/APEXnote#1]
Im using APEX5.1 and i want to use Theme APEX5.0, workable from APEX internal application, such as f4000, f4550, instead of Universal Theme(42).

For that, i followed your post Use Theme: APEX 5.0 , but I did not know how to implement the 2 themes:
- f4000_theme.sql : for Home Page
- f4550_theme.sql : for Login Page
into one application containing 2 Pages: Login and Home

You can see my result on apex.oracle.com with this credentials:
Workspace: ws_formation
Username: asoukaina
Password: *******

I used the Application 100708 - Empty App from 3

I also get the 2 applications in apex.oracle.com
Application 52213 - f4000 Theme APEX 5.0 DEMO
Application 62077 - f4550 Theme APEX 5.0 DEMO
but i get errors in theme.

Thank you for help in advance.

**Comment by iMingLei** [comment]
Hi @dpccrt87 ,

Now you can access your application 52213 with demo/demo. I think the problem was I kept copies online as same alias as the ones you exported to your own workspace. After I changed the aliases for both two apps, now your apps and my ones work properly. It's better to change them with your own alias like: THEME_APEX50_4000_DPCxx

If you want to merge two themes to one app, you can copy these diff templates from the app which you don't want to keep to the major one which you want to keep. I did't try but I think this should work.

ps: it's better to change your workspace password and remove it from the comment and also my blogger for safety. :)

Merci.

**Comment by dpccrt87** [comment]
Hi @iMingLei, 
Thanks a lot for your help.
I changed the password as requested.
